name: Run Test - Desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run wd:update
      - run: npm run test:desktop
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          path: reports/index.html
