name: Run Test - Mobile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run wd:update
      - run: npm run test:mobile
      - name: report
      - uses: actions/upload-artifact@v2
        with:
         name: report
         path: reports/index.html
